version: 0.2
env:
  variables:
    TOKEN: "sqp_5cc96f0f85cafb1f9daffb616c1b19e4ed06c76c"
    HOST: "http://52.213.36.86:9000"
    PROJECTKEY: "Hariharan-Sathiyamoorthy_jobhunt_5191cfdd-ad36-4510-9f04-962d8ce1a4d1"
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
  build:
    commands:
      - ./sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -Dsonar.projectKey=$PROJECTKEY -Dsonar.sources=. -Dsonar.host.url=$HOST -Dsonar.login=$TOKEN
      - curl $HOST/api/qualitygates/project_status?projectKey=$PROJECTKEY > result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then exit 1 ;fi

