# Generated by Django 5.0.3 on 2024-03-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applied',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Applied'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Interview'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Offer'},
        ),
        migrations.AlterModelOptions(
            name='rejected',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Rejected'},
        ),
        migrations.AlterModelOptions(
            name='whislist',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Whislist'},
        ),
    ]
