# Generated by Django 5.0.3 on 2024-03-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_applied_options_alter_interview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='move_to_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='move_to_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='move_to_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whislist',
            name='move_to_applied',
            field=models.BooleanField(default=False),
        ),
    ]
