# Generated by Django 5.0.3 on 2024-03-09 20:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_applied_move_to_rejected_interview_move_to_offer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whislist',
            new_name='Whishlist',
        ),
        migrations.AlterModelOptions(
            name='whishlist',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Whishlist'},
        ),
    ]
