# Generated by Django 5.0.3 on 2024-03-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_whislist_whishlist_alter_whishlist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='move_to_interview',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
